### ISSUE TITLE
How important is the database?

### ISSUE THREAD

**Issue by Nebucatnetzer** [zhaofengli/attic#125]
Can we reconstruct the database from the files or do we have to delete the whole cache when the DB gets lost?

**Comment by cole-h** [comment]
As far as I understand, the database is the source of truth. Without it, there's no way to go from `stored chunk(s)` to `nar`, since the chunks are just named `{random_uuid}.chunk`.

**Comment by Nebucatnetzer** [comment]
Makes sense thank you.
