### ISSUE TITLE
Error: relative URL without a base

### ISSUE THREAD

**Issue by DerDennisOP** [zhaofengli/attic#129]
I'm trying to push to my attic store, but I'm just getting this error:
```
> attic use main
Configuring Nix to use "main" on "local":
+ Substituter: attic.wavelens.iomain
+ Trusted Public Key: main:***********************************
+ Access Token
Error: relative URL without a base
> attic watch-store main                                                     
Error: relative URL without a base
```

Any Ideas on how to fix?

**Comment by cole-h** [comment]
It looks like you're missing the protocol part of the URL. If you change your substituter URL to `http(s)://attic.wavelens.iomain`, it should work again.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=498bb108b3ec599bfc0d6f530d1b2705

**Comment by pcboy** [comment]
I'm encountering a similar issue and I don't get it.

I did:

```shell
> attic login my-cache http://localhost:9393 eyJhbGci...
✍️ Configuring server "my-cache"
```

So at this stage it seems everything is fine.
But then I tried to do:

```shell
> attic use my-cache
Error: relative URL with a cannot-be-a-base base
> attic cache create hello
Error: relative URL with a cannot-be-a-base base
```

What am I missing? :thinking:

**Comment by pcboy** [comment]
I managed to fix it, but not sure I understand why.  I did:

```shell
> attic login local http://localhost:9393 eyJhbGciO...
✍️ Overwriting server "local"
```

After this, I was able to do `attic use local` and I was also able to re-do `attic login my-cache https://localhost:9393 eyJhB...` and this time `attic use my-cache` worked with no issue.
