### ISSUE TITLE
Support for asynchronous uploading

### ISSUE THREAD

**Issue by ghost** [zhaofengli/attic#18]
I think it would be quite helpful if the attic client supported asynchronous uploading when using it via the nix post-build-hook.

Maybe the client could write the paths of the binaries to a file and another instance of the client (via systemd) could be watching said file and upload all binaries that appear.

Is this something you’d accept a PR for?

**Comment by zhaofengli** [comment]
That would be a nice feature that I'm willing to accept a PR for. I just added support for `watch-store`, and receiving store paths from Unix Domain Sockets can be implemented with [the same infrastructure](https://github.com/zhaofengli/attic/blob/d540cc6888959a284da187a689ced7386324c09f/client/src/push.rs#L79-L100).
