### ISSUE TITLE
Allow using NixOS module with attic from Nixpkgs

### ISSUE THREAD

**Issue by msfjarvis** [zhaofengli/attic#183]
Currently the NixOS module for attic also injects this repository's version of `attic-client` and `attic-server` via [an overlay](https://github.com/zhaofengli/attic/blob/1b29816235b7573fca7f964709fd201e1a187024/flake/nixos.nix#L12), this prevents me from being able to rely on the NixOS binary cache and results in rather costly rebuilds of the server every time I update my flake inputs. If it was possible to expose an option to disable the overlay or a new module without the overlay it would be of tremendous help.

I'm willing to send in a PR for either approach if you're open to them.

**Comment by jzbor** [comment]
I use these two options  to use the module with the package from nixpkgs:
```nix
    services.atticd = {
      enable = true;
      package = pkgs.attic-server;
    };
```

**Comment by msfjarvis** [comment]
I don't think that actually works. The `atticd` NixOS module also sets `useFlakeCompatOverlay = false;` but follows it up with unconditionally including the overlay: https://github.com/zhaofengli/attic/blob/1b29816235b7573fca7f964709fd201e1a187024/flake/nixos.nix#L11-L13

Nevertheless, I tried it anyway and Nix still tried to build `attic-0.1.0` which is the version from this repository, as opposed to `attic-0-unstable-2024-10-04` from `nixpkgs-unstable`.

**Comment by jzbor** [comment]
I think you will have to check this file instead:
https://github.com/zhaofengli/attic/blob/1b29816235b7573fca7f964709fd201e1a187024/nixos/atticd.nix

I just checked and it does use the package from `nixpkgs`. It would also be odd otherwise, because the machine I am running this on does not have enough ram to build the flake from source (learned that the hard way). How are you importing the module? I use `(inputs.attic + "/nixos/atticd.nix")`.

**Comment by adamcstephens** [comment]
FYI, the attic module has been ported to nixpkgs now for those who want to use it from there.

**Comment by LukeChannings** [comment]
It looks like there's a conflict between this repo's nixOS module and nixpkgs though:

```
The option `services.atticd.enable' in `/nix/store/0az17ihialzgdlg2r9jinzmh23dka8qz-source/nixos/modules/services/networking/atticd.nix' is already declared in `/nix/store/afh26jh8kjnak225cbab73galp9yipww-source/nixos/atticd.nix'
```

**Comment by theoparis** [comment]
I also ran into the conflict with the flake-based nixos module just now 👀
