### ISSUE TITLE
`atticd-atticadm` uses both `--same-dir` and `--working-directory /` for `systemd-run`

### ISSUE THREAD

**Issue by PJungkamp** [zhaofengli/attic#201]
https://github.com/zhaofengli/attic/blob/75d4dd962d5bab6a27a5f4e312a76eed3a10a470/nixos/atticd.nix#L45-L59

I don't think that this was intended. Should we drop the `--working-directory /`argument?

**Comment by zhaofengli** [comment]
To fix #26, the wrapper was made to opportunistically change the directory, and `--working-directory /` was added. Let's remove `--same-dir`.
