### ISSUE TITLE
Choose between different servers

### ISSUE THREAD

**Issue by gador** [zhaofengli/attic#25]
I'm trying to upload to two separate servers.

I use `attic login server1` and then `attic push cache_on_server_1` which works just fine.
When I then do: `attic login server2` and `attic push cache_on_server_2` I get `NoSuchCache: The requested cache does not exist.`

So, for some reason I'm not loged to the second server. 

If I use `attic login --set-default server2` the push works fine. 

Is this supposed to work like this? Or is there a way to set the upstream server somewhere else?

**Comment by zhaofengli** [comment]
The syntax is [`servername:cachename`](https://docs.attic.rs/user-guide/index.html#logging-in) if the server isn't the default, like `server2:cache_on_server_2`.

**Comment by gador** [comment]
ah ok, thanks!
