### ISSUE TITLE
attic watch-store seems to be leaking memory

### ISSUE THREAD

**Issue by fd** [zhaofengli/attic#54]
`attic watch-store` seems to be leaking or holding onto memory over time.

I've been running many large builds on a set of self-hosted Github Actions Runners for the past two days. The GHA runners run 
in their own nixos-containers, `attic watch-store` runs on the host system (NixOS). The GHA runners share a nix daemon with the `attic watch-store`. Attic pushes out nix store paths just fine after they have been build by the runners. The whole setup runs on a system with 8GiB memory which should be sufficient for doing build coordination (the actual builds happen on different machines). But as the number of paths that attic had to check/upload grows, so does its memory use.

Maybe attic is holding onto some buffers while uploading, this would explain the RSS size. Maybe attic tries to know which paths were previously uploaded in an inefficient manner, but I doubt that tracking a couple of thousands of checked/uploaded nix paths would take up ~8GiB.

Anyways, really like this project! Thank you for putting in the work.

**Comment by fd** [comment]
Oh, as an additional note: I just noticed while looking at the logs that `attic watch-store` had uploaded about 8GiB of data before I restarted the systemd service. So this seems to be more than a coincidence.

**Comment by fd** [comment]
🏓 @zhaofengli

**Comment by zhaofengli** [comment]
Oops, missed this one. `watch-store` does [keep track](https://github.com/zhaofengli/attic/blob/564b4be0f90ae5f9a524521e17a8b5ff0327f43a/client/src/push.rs#L349) of all store paths that have already been uploaded so it doesn't need to ask the server about the same paths again. However, it shouldn't take up that much space. Another possibility is that there may be some leak coming from the C++ interop with `libnixstore`. I'll take a look.

**Comment by fd** [comment]
I cannot replicate the behavior anymore so I guess it is fixed now.
