### ISSUE TITLE
~/.config/attic/config.toml is word-readable

### ISSUE THREAD

**Issue by bbigras** [zhaofengli/attic#6]
I guess it's created when we use `attic login` and seems to be `rw-r--r--`. I guess it should be 600.

Same thing for `~/.config/nix/netrc`.

**Comment by zhaofengli** [comment]
Oof. Fixed in 384e7aa92d34062d2b46313c539bb52fd7913371 and 70ed4772088cd19979a703325175a4450d734179. Existing config files aren't affected until a write happens.
